import { test, expect } from '@playwright/test';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { mkdtemp, mkdir, readFile, writeFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createPublisher } from '../scripts/auto-publish.mjs';

const exec = promisify(execFile);

test('publisher skips timestamp-only changes and pushes only data changes in an isolated clone', async () => {
  const root = await mkdtemp(join(tmpdir(), 'match-publish-'));
  const origin = join(root, 'remote.git');
  const seed = join(root, 'seed');
  const workDir = join(root, 'publisher');
  const git = args => exec('git', args, { cwd: seed });
  try {
    await mkdir(seed);
    await exec('git', ['init', '--bare', '--initial-branch=main', origin]);
    await git(['init', '--initial-branch=main']);
    const initial = JSON.parse(await readFile(new URL('../match-data.json', import.meta.url), 'utf8'));
    await writeFile(join(seed, 'match-data.json'), JSON.stringify(initial));
    await writeFile(join(seed, 'forecast-history.json'), JSON.stringify({ version: 1, forecasts: [] }));
    await writeFile(join(seed, 'app.js'), '// unrelated code\n');
    await git(['add', '.']);
    await git(['-c', 'user.name=Test', '-c', 'user.email=test@example.com', 'commit', '-m', 'initial']);
    await git(['remote', 'add', 'origin', origin]);
    await git(['push', '-u', 'origin', 'main']);
    const originalHead = (await git(['rev-parse', 'HEAD'])).stdout.trim();
    let changeData = false;
    let changeWind = false;
    let ticks = 0;
    const logs = [];
    let deploymentState = 'failed';
    let reruns = 0;
    const deploymentHeads = [];
    const publish = createPublisher({ repoUrl: origin, workDir, retryDeployment: true, rerun: async () => { reruns++; }, deploymentCheck: async ({ sha }) => { deploymentHeads.push(sha); return { state: deploymentState, runId: 123, message: 'Pages 部署失败' }; }, logger: message => logs.push(message), syncData: async dir => {
      const snapshot = JSON.parse(await readFile(join(dir, 'match-data.json'), 'utf8'));
      snapshot.fetchedAt = `2026-09-30T04:0${++ticks}:00Z`;
      snapshot.wind = { ...snapshot.wind, fetchedAt: snapshot.fetchedAt };
      if (changeData) snapshot.events[0].slots[1].records = [{ name: 'New judgment', side: 'blue' }];
      if (changeWind) snapshot.wind.records = [{ name: 'Wind only', side: 'red', postedAt: '2026-09-30T10:05:00+08:00', match: '10点场' }];
      await writeFile(join(dir, 'match-data.json'), JSON.stringify(snapshot));
    } });
    const first = await publish();
    expect(first.published).toBe(false);
    expect(first.deployment.state).toBe('pending');
    expect(reruns).toBe(1);
    await git(['fetch', 'origin']);
    expect((await git(['rev-parse', 'origin/main'])).stdout.trim()).toBe(originalHead);
    const failedAgain = await publish();
    expect(failedAgain.deployment.state).toBe('failed');
    expect(reruns).toBe(1); // 同一失败流程不无限重跑
    deploymentState = 'live';
    expect((await publish()).deployment.state).toBe('live');
    expect(deploymentHeads.every(sha => sha === originalHead)).toBe(true);
    changeData = true;
    expect((await publish()).published).toBe(true);
    expect(logs.some(line => line.includes('原表同步成功，抓取时间：'))).toBe(true);
    expect(logs.some(line => line.includes('开始推送 main'))).toBe(true);
    expect(logs.some(line => line.includes('https://yysrank.com/dyjc.html'))).toBe(true);
    expect(logs.some(line => line.includes('对弈风向同步成功，抓取时间：'))).toBe(true);
    await git(['fetch', 'origin']);
    const changedHead = (await git(['rev-parse', 'origin/main'])).stdout.trim();
    expect(changedHead).not.toBe(originalHead);
    expect((await git(['diff', '--name-only', originalHead, changedHead])).stdout.trim()).toBe('match-data.json');
    expect((await publish()).published).toBe(false);
    await git(['fetch', 'origin']);
    expect((await git(['rev-parse', 'origin/main'])).stdout.trim()).toBe(changedHead);
    changeWind = true;
    expect((await publish()).published).toBe(true);
    await git(['fetch', 'origin']);
    const windHead = (await git(['rev-parse', 'origin/main'])).stdout.trim();
    expect(windHead).not.toBe(changedHead);
    expect((await git(['diff', '--name-only', changedHead, windHead])).stdout.trim()).toBe('match-data.json');
    expect((await publish()).published).toBe(false);
    expect(await readFile(join(seed, 'app.js'), 'utf8')).toBe('// unrelated code\n');
    expect(JSON.parse(await readFile(join(seed, 'match-data.json'), 'utf8')).fetchedAt).toBe(initial.fetchedAt);
  } finally { await rm(root, { recursive: true, force: true }); }
});
